# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_multiedit.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MultiEdit(object):
    def setupUi(self, MultiEdit):
        MultiEdit.setObjectName("MultiEdit")
        MultiEdit.resize(801, 517)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        MultiEdit.setFont(font)
        self.label = QtWidgets.QLabel(MultiEdit)
        self.label.setGeometry(QtCore.QRect(20, 60, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MultiEdit)
        self.label_2.setGeometry(QtCore.QRect(20, 119, 67, 17))
        self.label_2.setObjectName("label_2")
        self.oldattribute = QtWidgets.QComboBox(MultiEdit)
        self.oldattribute.setGeometry(QtCore.QRect(10, 200, 261, 27))
        self.oldattribute.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.oldattribute.setObjectName("oldattribute")
        self.label_3 = QtWidgets.QLabel(MultiEdit)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 141, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(MultiEdit)
        self.label_4.setGeometry(QtCore.QRect(300, 180, 161, 17))
        self.label_4.setObjectName("label_4")
        self.txtFeedBack = QtWidgets.QTextBrowser(MultiEdit)
        self.txtFeedBack.setGeometry(QtCore.QRect(10, 360, 781, 131))
        self.txtFeedBack.setObjectName("txtFeedBack")
        self.line = QtWidgets.QFrame(MultiEdit)
        self.line.setGeometry(QtCore.QRect(10, 50, 841, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(MultiEdit)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 351, 41))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.select = QtWidgets.QPushButton(MultiEdit)
        self.select.setGeometry(QtCore.QRect(20, 240, 111, 41))
        self.select.setObjectName("select")
        self.unselect = QtWidgets.QPushButton(MultiEdit)
        self.unselect.setGeometry(QtCore.QRect(140, 240, 121, 41))
        self.unselect.setObjectName("unselect")
        self.change_another = QtWidgets.QPushButton(MultiEdit)
        self.change_another.setGeometry(QtCore.QRect(440, 250, 171, 41))
        self.change_another.setObjectName("change_another")
        self.label_6 = QtWidgets.QLabel(MultiEdit)
        self.label_6.setGeometry(QtCore.QRect(293, 59, 261, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(MultiEdit)
        self.label_7.setGeometry(QtCore.QRect(10, 343, 81, 20))
        self.label_7.setObjectName("label_7")
        self.Exit = QtWidgets.QPushButton(MultiEdit)
        self.Exit.setGeometry(QtCore.QRect(620, 310, 171, 41))
        self.Exit.setObjectName("Exit")
        self.save = QtWidgets.QPushButton(MultiEdit)
        self.save.setGeometry(QtCore.QRect(617, 250, 171, 41))
        self.save.setObjectName("save")
        self.show_t = QtWidgets.QPushButton(MultiEdit)
        self.show_t.setGeometry(QtCore.QRect(440, 310, 171, 41))
        self.show_t.setObjectName("show_t")
        self.fieldtype = QtWidgets.QComboBox(MultiEdit)
        self.fieldtype.setGeometry(QtCore.QRect(577, 138, 71, 27))
        self.fieldtype.setObjectName("fieldtype")
        self.fieldtype.addItem("")
        self.fieldtype.addItem("")
        self.fieldtype.addItem("")
        self.create_new_field = QtWidgets.QPushButton(MultiEdit)
        self.create_new_field.setGeometry(QtCore.QRect(650, 138, 141, 27))
        self.create_new_field.setObjectName("create_new_field")
        self.line_6 = QtWidgets.QFrame(MultiEdit)
        self.line_6.setGeometry(QtCore.QRect(283, 290, 511, 20))
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.label_8 = QtWidgets.QLabel(MultiEdit)
        self.label_8.setGeometry(QtCore.QRect(584, 60, 201, 17))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(MultiEdit)
        self.label_10.setGeometry(QtCore.QRect(580, 120, 161, 17))
        self.label_10.setObjectName("label_10")
        self.newvalue = QtWidgets.QLineEdit(MultiEdit)
        self.newvalue.setGeometry(QtCore.QRect(296, 201, 491, 27))
        self.newvalue.setObjectName("newvalue")
        self.newfield = QtWidgets.QLineEdit(MultiEdit)
        self.newfield.setGeometry(QtCore.QRect(574, 80, 220, 27))
        self.newfield.setObjectName("newfield")
        self.label_12 = QtWidgets.QLabel(MultiEdit)
        self.label_12.setGeometry(QtCore.QRect(350, 10, 51, 41))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/plugins/MultiEdit/pienocampo.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.line_3 = QtWidgets.QFrame(MultiEdit)
        self.line_3.setGeometry(QtCore.QRect(270, 60, 20, 271))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_2 = QtWidgets.QFrame(MultiEdit)
        self.line_2.setGeometry(QtCore.QRect(560, 60, 20, 111))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(MultiEdit)
        self.line_4.setGeometry(QtCore.QRect(570, 166, 221, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.about = QtWidgets.QPushButton(MultiEdit)
        self.about.setGeometry(QtCore.QRect(610, 10, 171, 41))
        self.about.setObjectName("about")
        self.all = QtWidgets.QPushButton(MultiEdit)
        self.all.setGeometry(QtCore.QRect(20, 290, 111, 21))
        self.all.setObjectName("all")
        self.line_7 = QtWidgets.QFrame(MultiEdit)
        self.line_7.setGeometry(QtCore.QRect(10, 320, 271, 20))
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.label_9 = QtWidgets.QLabel(MultiEdit)
        self.label_9.setGeometry(QtCore.QRect(400, 20, 131, 21))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/plugins/MultiEdit/d2gis.com.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.chosenlayer = QgsMapLayerComboBox(MultiEdit)
        self.chosenlayer.setGeometry(QtCore.QRect(70, 60, 211, 31))
        self.chosenlayer.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.chosenlayer.setObjectName("chosenlayer")
        self.Column = QgsFieldComboBox(MultiEdit)
        self.Column.setGeometry(QtCore.QRect(69, 110, 211, 31))
        self.Column.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.Column.setObjectName("Column")
        self.new_field = QgsFieldComboBox(MultiEdit)
        self.new_field.setGeometry(QtCore.QRect(290, 80, 241, 27))
        self.new_field.setObjectName("new_field")
        self.label.raise_()
        self.label_2.raise_()
        self.oldattribute.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.txtFeedBack.raise_()
        self.line.raise_()
        self.select.raise_()
        self.unselect.raise_()
        self.change_another.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.Exit.raise_()
        self.save.raise_()
        self.show_t.raise_()
        self.fieldtype.raise_()
        self.create_new_field.raise_()
        self.line_6.raise_()
        self.label_8.raise_()
        self.label_10.raise_()
        self.newvalue.raise_()
        self.newfield.raise_()
        self.label_12.raise_()
        self.line_3.raise_()
        self.line_2.raise_()
        self.line_4.raise_()
        self.about.raise_()
        self.all.raise_()
        self.line_7.raise_()
        self.label_9.raise_()
        self.label_5.raise_()
        self.chosenlayer.raise_()
        self.Column.raise_()
        self.new_field.raise_()

        self.retranslateUi(MultiEdit)
        self.Exit.clicked['bool'].connect(MultiEdit.reject)
        QtCore.QMetaObject.connectSlotsByName(MultiEdit)

    def retranslateUi(self, MultiEdit):
        _translate = QtCore.QCoreApplication.translate
        MultiEdit.setWindowTitle(_translate("MultiEdit", "MultiEdit"))
        self.label.setText(_translate("MultiEdit", "Layer"))
        self.label_2.setText(_translate("MultiEdit", "Field"))
        self.label_3.setText(_translate("MultiEdit", "Old Attribute value"))
        self.label_4.setText(_translate("MultiEdit", "New Attribute value"))
        self.label_5.setText(_translate("MultiEdit", "MultiEdit 1.1  (C) 2018 by Giuseppe De Marco   \n"
"www.d2gis.com"))
        self.select.setText(_translate("MultiEdit", "Select\n"
"Features"))
        self.unselect.setText(_translate("MultiEdit", "Clear Selected\n"
"Features"))
        self.change_another.setText(_translate("MultiEdit", "Write value \n"
" to chosen field"))
        self.label_6.setText(_translate("MultiEdit", "Field to write the new value to:"))
        self.label_7.setText(_translate("MultiEdit", "Messages"))
        self.Exit.setText(_translate("MultiEdit", "Exit"))
        self.save.setText(_translate("MultiEdit", "Save Changes"))
        self.show_t.setText(_translate("MultiEdit", "Show Attribute Table \n"
"of selected Layer"))
        self.fieldtype.setItemText(0, _translate("MultiEdit", "String"))
        self.fieldtype.setItemText(1, _translate("MultiEdit", "Int"))
        self.fieldtype.setItemText(2, _translate("MultiEdit", "Double"))
        self.create_new_field.setText(_translate("MultiEdit", "Create new Field"))
        self.label_8.setText(_translate("MultiEdit", "New Field Name"))
        self.label_10.setText(_translate("MultiEdit", "Field type"))
        self.about.setText(_translate("MultiEdit", "About/Help"))
        self.all.setText(_translate("MultiEdit", "Select All"))

from qgis.gui import QgsFieldComboBox
from qgis.gui import QgsMapLayerComboBox
import resources_rc
